### ISSUE TITLE
useContractReader return type doesn't match the generic type specified

### ISSUE THREAD

**Issue by grothem** [austintgriffith/eth-hooks#112]
I'm trying to use the useContractReader hook, like this:

```ts
  const vendorApproval = useContractReader<BigNumber>(yourTokenContract, {
    contractName: 'YourToken',
    functionName: 'allowance',
    functionArgs: [address, vendorContract?.address],
  });
```

I was expecting the `vendorApproval` to be of type `BigNumber`,  however, at runtime, the type is actually `BigNumber[]`

**Comment by ShravanSunder** [comment]
typescript doesn't enforce types during runtime.  It is probably the contract definition.

**Comment by ShravanSunder** [comment]
@grothem revisiting,  i think its a typechain issue.  I've opened a ticket with typechain https://github.com/dethcrypto/TypeChain/issues/590

**Comment by ShravanSunder** [comment]
i've created a workaround for now.  hopefully its fine until typechain resolves things.
