### ISSUE TITLE
Add test for new useContractReader

### ISSUE THREAD

**Issue by ShravanSunder** [austintgriffith/eth-hooks#122]
Use **Hook test strategy** mentioned in: https://github.com/scaffold-eth/eth-hooks/issues/118#issue-1092134285

## Additional tests (other than specified in strategy)
Test with using an event with an update option.  
- hook should update when event is fired
- It should disable other update options. 

Test  other update options without mocking

**Comment by ssp6** [comment]
Closed in PR [162](https://github.com/scaffold-eth/eth-hooks/pull/162)
