### ISSUE TITLE
Feature Request: pass list of args to useContractReader to read multiple return values

### ISSUE THREAD

**Issue by calvbore** [austintgriffith/eth-hooks#132]
Sometimes I find myself needing to read a contract function/variable with multiple different args, and since we can't use hooks in loops it becomes a bit of a chore. So, it would be cool to be able to pass a list of args to useContractReader and have a list returned corresponding to each of the provided arguments. 

I believe the useBalance hook operates in a similar way already for a list of addresses.

**Comment by ShravanSunder** [comment]
@calvbore would any other hook benefit from this?

**Comment by calvbore** [comment]
@ShravanSunder Just doing a quick skim through the hooks, haven't checked if something is implemented already or not, but maybe both the ENS hooks, and the useTokenBalance hook?
