### ISSUE TITLE
Issue with "Hooks" Docs in Mobile

### ISSUE THREAD

**Issue by adriandelgg** [austintgriffith/eth-hooks#158]
Hey guys, great work!

I was reading the docs on my Android and there seems to be some issues with it. I'm not sure if it's just my phone, but here's a screenshot of what I see.

The issue is in the "Hooks" API portion of the docs.

![Screenshot_20220118-085139.jpg](https://user-images.githubusercontent.com/32179921/149982130-33abaa19-053c-43ee-9388-4d68e63033d6.jpg)

**Comment by ShravanSunder** [comment]
using docusaurus now, so hopefully this is mitigated.
