### ISSUE TITLE
allow custom providers to eth-hooks EthersAppContext

### ISSUE THREAD

**Issue by ShravanSunder** [austintgriffith/eth-hooks#168]
https://twitter.com/timothyjcoulter/status/1486837152155529221

**Comment by tcoulter** [comment]
👀 👀 👀 👀 

Exactly what I was looking for. Thank you!

**Comment by ShravanSunder** [comment]
> 👀 👀 👀 👀
> 
> Exactly what I was looking for. Thank you!

@tcoulter it has been published with the `next` tag (>=4.0.24)
here is some docs:  https://github.com/scaffold-eth/eth-hooks/tree/docs#pass-in-a-provider-directly-into-ethersappcontext
