### ISSUE TITLE
`ethersContext.signer` does not change when metamask account changes

### ISSUE THREAD

**Issue by stephancill** [austintgriffith/eth-hooks#177]
### Expected behaviour
When connecting the account, it should show the same address for Signer and Account. After switching accounts in metamask it should show the new address for Signer and Account.

### Actual behaviour
When connecting the account, it shows the same address for Signer and Account. 
<img width="537" alt="Screenshot 2022-02-12 at 15 35 47" src="https://user-images.githubusercontent.com/5469870/153713612-385f914e-0191-4c2f-a76d-612bedf817ac.png">

After switching accounts in metamask it shows the old address for Signer and the new address for Account.
<img width="512" alt="Screenshot 2022-02-12 at 15 36 00" src="https://user-images.githubusercontent.com/5469870/153713625-cbd05c9a-d0fa-4f3f-8a01-5f451f886d48.png">

### To reproduce in React:
index.tsx
```typescript
import React from 'react';
import ReactDOM from 'react-dom';
import './index.css';
import App from './App';
import { EthersAppContext } from 'eth-hooks/context';

ReactDOM.render(
  <React.StrictMode>
    <EthersAppContext>
      <App />
    </EthersAppContext>
    
  </React.StrictMode>,
  document.getElementById('root')
);
```

App.tsx
```typescript
import { useSignerAddress } from 'eth-hooks';
import { useEthersContext } from 'eth-hooks/context';
import { ConnectButton } from './ConnectButton';

function App() {
  const ethersContext = useEthersContext();
  const {signer, account} = ethersContext
  const [signerAddrress] = useSignerAddress(signer)

  return (
    <div className="App">
      <ConnectButton/>
      <div>Signer: {signerAddrress}</div>
      <div>Account: {account}</div>
    </div>
  );
}

export default App;
```

ConnectButton.tsx
```typescript
import { EthersModalConnector, TEthersModalConnector, useEthersContext } from "eth-hooks/context";
import { useCallback } from "react";

type TCreateEthersModalConnector = (id?: string) => TEthersModalConnector;

export const ConnectButton = () => {
  const ethersContext = useEthersContext();

  const createLoginConnector: TCreateEthersModalConnector = useCallback(
    (id?: string) => {
      const connector = new EthersModalConnector(
        {},
        { reloadOnNetworkChange: false, immutableProvider: false },
        id
      );
      return connector;
    },
    []
  );

  // to handle a login
  const handleLoginClick = (): void => {
    if (createLoginConnector != null && ethersContext?.openModal != null) {
      const connector = createLoginConnector();
      ethersContext.openModal(connector);
    }
  };

  // to handle a log out
  const handleLogoutClick = (): void => {
    if (ethersContext?.disconnectModal != null) {
      ethersContext.disconnectModal();
    }
  };

  return (
    <div>
      <div>
        {ethersContext.signer 
      ? 
        <button onClick={() => handleLogoutClick()}>Disconnect</button> 
      : 
        <button onClick={() => handleLoginClick()}>Connect</button>}
      </div>
    </div>
    
  )
}
```

**Comment by stephancill** [comment]
I think this is also related to the `useSignerAddress` hook because with the fix implemented in #178, running the test scenario again, logging `ethersContext.signer` when it changes:

Initial connect:
<img width="824" alt="Screenshot 2022-02-12 at 23 27 22" src="https://user-images.githubusercontent.com/5469870/153729042-921714cb-fecf-44f2-8559-cc1217156794.png">


After changing accounts, the signer on `ethersContext` is correct but the result of `useSignerAddress` is still outdated:
<img width="794" alt="Screenshot 2022-02-12 at 23 27 37" src="https://user-images.githubusercontent.com/5469870/153729049-d225c406-2576-48ff-ba84-f1caa31f150f.png">

**Comment by dvinubius** [comment]
I've been experiencing this issue for many days now and didn't know what was going on.

But it came with another symptom, and I kept blaming Metamask for it: my transactions would fail with a Metamask error saying  _RPC Error: Invalid parameters: must provide an Ethereum address_

Only accidentally I discovered that it was occurring when I was changing accounts in metamask: 

The header account was always updating correctly, so I never considered to check the context values. 
But indeed the ethersContext.signer would keep the old address. 

Only a page reload would fix the mismatch...

![Screenshot 2022-02-23 at 00 39 40](https://user-images.githubusercontent.com/32189942/155231622-cf8ce0f1-65df-4c22-8140-9067b6a9d0aa.png)

**Comment by dvinubius** [comment]
@ShravanSunder I've looked into it just a bit and it seems to be a bug in web3-react, rather than in eth-hooks

**Comment by dvinubius** [comment]
@stephancill have you found a suitable workaround?

For anyone having this issue and looking for a quick fix:

Create a helper like

```
export const getCurrentSigner = async () => {
  const ethereum = window.ethereum;
  // eslint-disable-next-line @typescript-eslint/no-unsafe-argument
  const provider = new ethers.providers.Web3Provider(ethereum);
  await provider.send('eth_requestAccounts', []);
  return provider.getSigner();
};
```

It works without making any other changes than this:

Instead of
`contract.functionCall(arg1, arg2)`
you can 
`contract.connect(await getCurrentSigner()).functionCall(arg1, arg2)`

**Comment by ShravanSunder** [comment]
pushed a change to update the signer field on change
