### ISSUE TITLE
Unclear instruction to integrate it with typescript

### ISSUE THREAD

**Issue by dellwatson** [austintgriffith/eth-hooks#186]
from #18 #53 , I'm not sure which version is ready for typescript?

**Comment by ShravanSunder** [comment]
not sure i understand your question?  all versions of eth-hooks were made for typescript

**Comment by dellwatson** [comment]
i tried v1-4,  in v1-3  have export issue. for v4 there are issues but not related to typescript (i quickly move out to othr ver).
so v4 probably should be working, i will confirm again later.

and as you [mentioned in other issues](https://github.com/scaffold-eth/eth-hooks/issues/86#issuecomment-1055517243) because 1-3 have differnt location
