### ISSUE TITLE
 errors using  nextjs

### ISSUE THREAD

**Issue by morandalex** [austintgriffith/eth-hooks#196]
I am trying to use eth-hooks with nextjs, but I am not understanding what is going wrong.

I created a test.js  in pages folder.

```js
import useGasPrice from "eth-hooks";
import React, {  useState } from "react";
import { NETWORKS } from "../helpers/constants";
const initialNetwork = NETWORKS.localhost; 

const test = ()=>{
    const networkOptions = [initialNetwork.name, "mainnet", "rinkeby"];

    const [selectedNetwork, setSelectedNetwork] = useState(networkOptions[0]);
  
    const targetNetwork = NETWORKS[selectedNetwork];
  
    const gasPrice =   useGasPrice(targetNetwork, "fast");
    console.log(gasPrice)
    
    return (<>test</>)
}

export default test ;
```

Then If start the application I get the following error:

![image](https://user-images.githubusercontent.com/9484568/161598219-8d6218cf-8fb6-4cf0-9ebd-34c29ecb2aa4.png)

so , I changed my next.config.js file with 

```js
const transpileModules = require("next-transpile-modules")

const withTM = transpileModules(["eth-hooks"])

module.exports = withTM({})
```

Finally,  if I restart the app ,  I get the following error:

![image](https://user-images.githubusercontent.com/9484568/161598518-c56372c9-66ea-4e75-aae0-e1d6cae8261e.png)

if I change the import statement in 

```js
import {useGasPrice} from "eth-hooks";

```
Then I get: 

![image](https://user-images.githubusercontent.com/9484568/161599421-0c7d16bd-6e6a-4f3f-a8e1-aa0065569a4c.png)

How to import the hook in next ?

**Comment by ShravanSunder** [comment]
you should be using named imports.
`import {useGasPrice} from "eth-hooks"`
