### ISSUE TITLE
Issue using v4 hooks with next.js 

### ISSUE THREAD

**Issue by dec3ntraliz3d** [austintgriffith/eth-hooks#197]
I am trying to use EthersAppContext with next.js but getting some errors. Any suggestion or example please? 

```import "../styles/globals.css";
import type { AppProps } from "next/app";
import { EthersAppContext } from "eth-hooks/context";

const App = ({ Component, pageProps }: AppProps) => {
  return (
    <EthersAppContext>
      <Component {...pageProps} />
    </EthersAppContext>
  );
};

export default App;
```

Error message
================

Type '{ children: Element; }' has no properties in common with type 'IntrinsicAttributes & TEthersAppContextProps'.ts(2559)

**Comment by ShravanSunder** [comment]
i haven't used next js before.  Have you tried wrapping `Component` in a div?

**Comment by ShravanSunder** [comment]
this issue is related to react 18.  see #204
