### ISSUE TITLE
Reference implementation for v4 and v5 beta?

### ISSUE THREAD

**Issue by ziad-saab** [austintgriffith/eth-hooks#246]
It looks like `eth-hooks` is currently being developed at v5 beta, but the `scaffold-eth` project is still using v2 from what I can see. Is there anywhere that has an implementation of a full dApp using the latest versions of `eth-ui` / `eth-hooks`?

**Comment by ShravanSunder** [comment]
@ziad-saab scaffold-eth-typescript has been on v4 and v5 for a while since jan this year.  https://github.com/scaffold-eth/scaffold-eth-typescript
